export const consumerHandlerAbi = [
    {
        type: "constructor",
        inputs: [
            { name: "dutchAuction_", type: "address", internalType: "address" },
            { name: "dataProvider_", type: "address", internalType: "address" },
            {
                name: "snapThreshold_",
                type: "uint256",
                internalType: "uint256",
            },
            { name: "targetDataType_", type: "string", internalType: "string" },
            { name: "gasLimit", type: "uint64", internalType: "uint64" },
        ],
        stateMutability: "payable",
    },
    { type: "receive", stateMutability: "payable" },
    {
        type: "function",
        name: "DATA_PROVIDER",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "DUTCH_AUCTION",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "OWNER",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "budget",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "completed",
        inputs: [],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "dataDeliveredSubId",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "onEvent",
        inputs: [
            { name: "emitter", type: "address", internalType: "address" },
            {
                name: "eventTopics",
                type: "bytes32[]",
                internalType: "bytes32[]",
            },
            { name: "data", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "priceTickSubId",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "snapThreshold",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "snapped",
        inputs: [],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "spent",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "supportsInterface",
        inputs: [
            { name: "interfaceId", type: "bytes4", internalType: "bytes4" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "targetDataType",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "withdraw",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "DataReceived",
        inputs: [
            {
                name: "auctionId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "price",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Snapped",
        inputs: [
            {
                name: "auctionId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "price",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    { type: "error", name: "EmptyDataType", inputs: [] },
    { type: "error", name: "EmptyFilter", inputs: [] },
    { type: "error", name: "GasLimitExceeded", inputs: [] },
    { type: "error", name: "GasLimitZero", inputs: [] },
    { type: "error", name: "HandlerZeroAddress", inputs: [] },
    { type: "error", name: "InsufficientBalance", inputs: [] },
    { type: "error", name: "InvalidMaxFeePerGas", inputs: [] },
    { type: "error", name: "OnlyOwner", inputs: [] },
    { type: "error", name: "OnlyReactivityPrecompile", inputs: [] },
    { type: "error", name: "UnsubscribeFailed", inputs: [] },
    { type: "error", name: "ZeroAddress", inputs: [] },
];
