export const dutchAuctionAbi = [
    {
        type: "constructor",
        inputs: [
            { name: "auctionClock_", type: "address", internalType: "address" },
            { name: "escrow_", type: "address", internalType: "address" },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "auctionClock",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "auctionCount",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "auctions",
        inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "id", type: "uint256", internalType: "uint256" },
            { name: "provider", type: "address", internalType: "address" },
            { name: "dataType", type: "string", internalType: "string" },
            { name: "apiUrl", type: "string", internalType: "string" },
            { name: "jsonSelector", type: "string", internalType: "string" },
            { name: "decimals", type: "uint8", internalType: "uint8" },
            { name: "startPrice", type: "uint256", internalType: "uint256" },
            { name: "floorPrice", type: "uint256", internalType: "uint256" },
            { name: "currentPrice", type: "uint256", internalType: "uint256" },
            { name: "priceStep", type: "uint256", internalType: "uint256" },
            { name: "startBlock", type: "uint256", internalType: "uint256" },
            { name: "timeoutBlocks", type: "uint256", internalType: "uint256" },
            {
                name: "status",
                type: "uint8",
                internalType: "enum IDutchAuction.AuctionStatus",
            },
            { name: "winner", type: "address", internalType: "address" },
            { name: "escrowRef", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "dropPrice",
        inputs: [
            { name: "auctionId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "escrow",
        inputs: [],
        outputs: [
            { name: "", type: "address", internalType: "contract IEscrow" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getActiveAuctions",
        inputs: [],
        outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getAuction",
        inputs: [
            { name: "auctionId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [
            {
                name: "",
                type: "tuple",
                internalType: "struct IDutchAuction.Auction",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    {
                        name: "provider",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "dataType",
                        type: "string",
                        internalType: "string",
                    },
                    { name: "apiUrl", type: "string", internalType: "string" },
                    {
                        name: "jsonSelector",
                        type: "string",
                        internalType: "string",
                    },
                    { name: "decimals", type: "uint8", internalType: "uint8" },
                    {
                        name: "startPrice",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "floorPrice",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "currentPrice",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "priceStep",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "startBlock",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "timeoutBlocks",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "status",
                        type: "uint8",
                        internalType: "enum IDutchAuction.AuctionStatus",
                    },
                    {
                        name: "winner",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "escrowRef",
                        type: "uint256",
                        internalType: "uint256",
                    },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "snap",
        inputs: [
            { name: "auctionId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "payable",
    },
    {
        type: "function",
        name: "startAuction",
        inputs: [
            { name: "dataType", type: "string", internalType: "string" },
            { name: "apiUrl", type: "string", internalType: "string" },
            { name: "jsonSelector", type: "string", internalType: "string" },
            { name: "decimals", type: "uint8", internalType: "uint8" },
            { name: "startPrice", type: "uint256", internalType: "uint256" },
            { name: "floorPrice", type: "uint256", internalType: "uint256" },
            { name: "priceStep", type: "uint256", internalType: "uint256" },
            { name: "timeoutBlocks", type: "uint256", internalType: "uint256" },
        ],
        outputs: [
            { name: "auctionId", type: "uint256", internalType: "uint256" },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "AuctionExpired",
        inputs: [
            {
                name: "auctionId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AuctionSnapped",
        inputs: [
            {
                name: "auctionId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "winner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "finalPrice",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AuctionStarted",
        inputs: [
            {
                name: "auctionId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "provider",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "dataType",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "startPrice",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "PriceTick",
        inputs: [
            {
                name: "auctionId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "newPrice",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "blockNumber",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    { type: "error", name: "AuctionNotActive", inputs: [] },
    { type: "error", name: "AuctionNotFound", inputs: [] },
    { type: "error", name: "EmptyApiUrl", inputs: [] },
    { type: "error", name: "EmptyDataType", inputs: [] },
    { type: "error", name: "EmptyJsonSelector", inputs: [] },
    { type: "error", name: "InsufficientPayment", inputs: [] },
    { type: "error", name: "InvalidPriceRange", inputs: [] },
    { type: "error", name: "InvalidPriceStep", inputs: [] },
    { type: "error", name: "InvalidTimeout", inputs: [] },
    { type: "error", name: "OnlyClock", inputs: [] },
    { type: "error", name: "ReentrancyGuard", inputs: [] },
    { type: "error", name: "RefundFailed", inputs: [] },
];
